name: Create Archive
on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set env version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'sbs_utils_${{ steps.get_version.outputs.VERSION }}.sbslib'
        exclusions: '*.git* /docs/* /mock/* /sphinx/* /tests/* *.py .nojekyll'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "sbs_utils_${{ steps.get_version.outputs.VERSION }}.sbslib"
        token: ${{ secrets.GITHUB_TOKEN }}