name: Create Archive
on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'sbs_utils_${{ env.CI_ACTION_REF_NAME }}.sbslib'
        exclusions: '*.git* /docs/* /mock/* /sphinx/* /tests/* *.py .nojekyll'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "sbs_utils_${{ env.CI_ACTION_REF_NAME }}.sbslib"
        token: ${{ secrets.GITHUB_TOKEN }}